### ISSUE TITLE
{'loss': 0.0, 'learning_rate': 1.6877637130801689e-07, 'epoch': 0.0}

### ISSUE THREAD

**Issue by whalefa1I** [PKU-YuanGroup/MoE-LLaVA#1]
```
{'loss': 2.1559, 'learning_rate': 8.438818565400844e-08, 'epoch': 0.0}                                                                                                                                               
{'loss': 0.0, 'learning_rate': 1.6877637130801689e-07, 'epoch': 0.0}                                                                                                                                                 
{'loss': 0.0, 'learning_rate': 2.5316455696202533e-07, 'epoch': 0.0}                                                                                                                                                 
{'loss': 0.0, 'learning_rate': 3.3755274261603377e-07, 'epoch': 0.0}                                                                                                                                                 
{'loss': 0.0, 'learning_rate': 4.219409282700422e-07, 'epoch': 0.0}                                                                                                                                                  
{'loss': 0.0, 'learning_rate': 5.063291139240507e-07, 'epoch': 0.0}                                                                                                                                                  
{'loss': 0.0, 'learning_rate': 5.907172995780591e-07, 'epoch': 0.0}                                                                                                                                                  
{'loss': 0.0, 'learning_rate': 6.751054852320675e-07, 'epoch': 0.0}                                                                                                                                                  
{'loss': 0.0, 'learning_rate': 7.59493670886076e-07, 'epoch': 0.0} 
```

During the pre-training phase, I can obtain the correct loss convergence. However, in the finetuning stage, except for the first iteration, the rest of the losses are all 0.0. Could you please tell me where the problem might be?

**Comment by LinB203** [comment]
I would like to know what version of transformers you use and what's your run command?

**Comment by whalefa1I** [comment]
> I would like to know what version of transformers you use and what's your run command? Any warnings during the run?
```
transformer-engine            1.2.0+c9f2b5e
transformers                  4.37.1
transformers-stream-generator 0.0.4
```
command
```
bash scripts/v1_5/phi2/finetune.sh
or
bash scripts/v1_5/qwen/finetune.sh
```
No warnings except
```
[2024-01-30 09:49:32,552] [WARNING] [runner.py:202:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
```

**Comment by LinB203** [comment]
I'm sorry we weren't able to reproduce your error. By the way when did you pull your code. We did have some minor bug fixes in the last few days. can you pull the latest code and try it?

![image](https://github.com/PKU-YuanGroup/MoE-LLaVA/assets/62638829/1e470ca0-43a7-443f-ba15-4b4210930b50)

**Comment by LinB203** [comment]
Inactive, close it. Feel free to open.

**Comment by whalefa1I** [comment]
> I'm sorry we weren't able to reproduce your error. By the way when did you pull your code. We did have some minor bug fixes in the last few days. can you pull the latest code and try it?
> 
> ![image](https://private-user-images.githubusercontent.com/62638829/300663093-1e470ca0-43a7-443f-ba15-4b4210930b50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTU5NTgsIm5iZiI6MTcwNjg1NTY1OCwicGF0aCI6Ii82MjYzODgyOS8zMDA2NjMwOTMtMWU0NzBjYTAtNDNhNy00NDNmLWJhMTUtNGI0MjEwOTMwYjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA2MzQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNWM3MzkwNDA5NjlmNjNiYmRlMTFkOThhZWM4NDU5YTBmNGQyOWQwZGIzYzI5YTBhMmRmMWY3YTg5MjVjMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VMv18s5JUY6vjWljaBVmkIeh1Jj_f5CrAgNbSVKV_Jk)

The problem is resolved after the deepspeed and accelerate versions are corrected. The previous deepspeed version is the latest version

**Comment by whalefa1I** [comment]
I got error like this:
```
AssertionError: The model has moe layers, but None of the param groups are marked as MoE. Create a param group with 'moe' key set to True before creating optimizer
```
Should I do anything before running stage3, such as convert the model

**Comment by LinB203** [comment]
Can not zero3 with MoE. https://github.com/microsoft/DeepSpeed/issues/2870
You can use `zero2_offload.json` to support bigger batch size.

**Comment by whalefa1I** [comment]
> Can not zero3 with MoE. [microsoft/DeepSpeed#2870](https://github.com/microsoft/DeepSpeed/issues/2870) You can use `zero2_offload.json` to support bigger batch size.

but Im using this config `scripts/zero2.json`

**Comment by LinB203** [comment]
Can you check whether the model goes into this `if` branch?

It should be executed when moe is turned on.

https://github.com/PKU-YuanGroup/MoE-LLaVA/blob/main/moellava/train/llava_trainer.py#L221

**Comment by whalefa1I** [comment]
> Can you check whether the model goes into this `if` branch?
> 
> It should be executed when moe is turned on.
> 
> https://github.com/PKU-YuanGroup/MoE-LLaVA/blob/main/moellava/train/llava_trainer.py#L221
<img width="1243" alt="截屏2024-02-02 22 10 02" src="https://github.com/PKU-YuanGroup/MoE-LLaVA/assets/32239722/11a64ff7-7ff3-4f15-935f-3251a6015319">

I think it's in the right line

**Comment by whalefa1I** [comment]
> Sorry, this issue has already finished. Could you raise a new issue and post your command & transformers version & deepspeed version & torch version. Thanks.

It's okay. I'll check my codes first. Happy Friday

**Comment by LinB203** [comment]
> > Sorry, this issue has already finished. Could you raise a new issue and post your command & transformers version & deepspeed version & torch version. Thanks.
> 
> It's okay. I'll check my codes first. Happy Friday

That's our mistake. Checking out this issue. 
https://github.com/PKU-YuanGroup/MoE-LLaVA/issues/17#issuecomment-1925237894
