### ISSUE TITLE
Openchat, quantisation, multiimage

### ISSUE THREAD

**Issue by sujitvasanth** [PKU-YuanGroup/MoE-LLaVA#13]
1. Please release the Moe-Llava-openchat model on hugging face (you have an example of training this on your training.sh)

2. Is it possible to use quatisation with image-to-text pipelines in transformers?
the reason for this is that openchat performs well on quantized gptq https://huggingface.co/TheBloke/openchat-3.5-0106-GPTQ

3. your video-llava model offers image to video comparison. does this model support image-to-image comparison? if so please show an example pythomn transformers example with/without pipeline

**Comment by LinB203** [comment]
1. We have uploaded [here](https://huggingface.co/LanguageBind/MoE-LLaVA-OpenChat-7B-4e). But the performance of MoE-LLaVA-OpenChat may only be comparable to MoE-LLaVA-Phi2. We are in the process of training a better performing OpenChat, but as a baseline, you can experience this version of MoE-LLaVA-OpenChat first.
2. Sorry, no plans for that in the short term.
3. Multi-image comparison is not supported at the moment, we'll get it done in the next month.

**Comment by sujitvasanth** [comment]
@LinB203 thge originall openchat7b v1102 is only 18Gb https://huggingface.co/openchat/openchat-3.5-1210/tree/main why is your vision model 30+Gb?. It wont fit on my rtx 3090 even for inference so will only be usable in the could or by researchers.
this is why I suggested quantisation....[ huggingface.co/openchat/openchat-3.5-1210](https://huggingface.co/TheBloke/openchat-3.5-0106-GPTQ)  which is only 4gb
great that you will training multi-image comparison..

**Comment by LinB203** [comment]
The released model weight is not vision model but a multimodal model with moe layer. So it is normal that the size of model is bigger than the original OpenChat. I will consider your suggestion. Thansk!

**Comment by sujitvasanth** [comment]
I wonder if it is possible to use the bitsandbytes library to quantize MoE-LLaVA-OpenChat  via transformers library or even direct from your inference demo with deepspeed..Im going to have a look at getting a few vision to text models running with bitandbytes quatisation - these models can be saved and reusedin their quantised form too..according to the documentation.. it would then fit on my 3090 gpu
