### ISSUE TITLE
Can the author elaborate a bit more about how the stage 3 was achieved?

### ISSUE THREAD

**Issue by CanyonWind** [PKU-YuanGroup/MoE-LLaVA#2]
Awesome work. Just a quick question, when converting from LVLM to MoE-LVLM, wonder whether the FF layer weights are split into smaller experts or are they duplicated? Any code reference for that would be really helpful to understand the details

**Comment by LinB203** [comment]
FFN weights are replicated without being divided into smaller experts. See deepspeed's moe implementation.
https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/moe/layer.py#L70

The corresponding calling code in our MoE-LLaVA.
https://github.com/PKU-YuanGroup/MoE-LLaVA/blob/main/moellava/model/language_model/llava_phi_moe.py#L428

By the way, our paper has been released just now.
https://arxiv.org/abs/2401.15947

**Comment by CanyonWind** [comment]
Cool, thanks for the prompt response.
