### ISSUE TITLE
paper和readme指标不一致

### ISSUE THREAD

**Issue by sxu1997** [PKU-YuanGroup/MoE-LLaVA#22]
paper和readme指标不一致，请问以哪个为准？

**Comment by sxu1997** [comment]
![Uploading Snipaste_2024-02-04_13-45-19.png…]()

**Comment by LinB203** [comment]
以Readme为准, 我们正在更新arxiv，预计1-2天后更新完毕。
[En] We are updating results in arxiv, it will be updated after 1-2 days.

**Comment by LinB203** [comment]
The paper has been updated.
https://arxiv.org/pdf/2401.15947.pdf
