### ISSUE TITLE
是否支持启动的时候，指定use_flash_attion_2 ??

### ISSUE THREAD

**Issue by awzhgw** [PKU-YuanGroup/MoE-LLaVA#25]
是否支持启动的时候，指定use_flash_attion_2 ??

**Comment by LinB203** [comment]
支持。参考以下代码。除了Qwen以外都可以这样，因为Qwen会自动开启。
[En] It supports, just modify the code as follows except the Qwen-based, because it will auto-enable the flash-attn.

```Python
model = LlavaPhiForCausalLM.from_pretrained(
                    model_args.model_name_or_path,
                    cache_dir=training_args.cache_dir,
                    attn_implementation="flash_attention_2",  # add this line
                    **bnb_model_from_pretrained_args
                )
```

**Comment by LinB203** [comment]
Hi, we have tested the flash attention2, but we found the performance degradation. We found the same question....
Therefore, we do not recommend you guys to enable the flash attention2.
https://github.com/huggingface/transformers/issues/28488
