### ISSUE TITLE
Method to Replicate Results from Huggingface Spaces

### ISSUE THREAD

**Issue by hiroalchem** [PKU-YuanGroup/MoE-LLaVA#3]
I tried Huggingface Spaces and got wonderful results. Thank you. How can I replicate these results locally?

**Comment by LinB203** [comment]
HF demo locally: https://github.com/PKU-YuanGroup/MoE-LLaVA?tab=readme-ov-file#-demo

CLI inference: https://github.com/PKU-YuanGroup/MoE-LLaVA?tab=readme-ov-file#cli-inference

Our API to use: https://github.com/PKU-YuanGroup/MoE-LLaVA?tab=readme-ov-file#-api

**Comment by hiroalchem** [comment]
@LinB203 Thank you for your response. There are several models shown, but which model is used in Huggingface Spaces?

**Comment by LinB203** [comment]
> @LinB203 Thank you for your response. There are several models shown, but which model is used in Huggingface Spaces?

Phi2.

**Comment by hiroalchem** [comment]
@LinB203 Thank you. I appreciate your response to my detailed questions.

**Comment by LinB203** [comment]
You're welcome. Btw, if you like our project, please give us a star ⭐ on GitHub for latest update.

> @LinB203 Thank you. I appreciate your response to my detailed questions.
