### ISSUE TITLE
Images for training

### ISSUE THREAD

**Issue by phellonchen** [PKU-YuanGroup/MoE-LLaVA#4]
Could you share the sampled images for Moe training, i.e. the images for Stage II SViT-157k, LVIS-220k  LRV-331k, MIMIC-IT-256k

**Comment by LinB203** [comment]
[here](https://github.com/PKU-YuanGroup/MoE-LLaVA/blob/main/docs/TRAIN.md#data-preparation) to download.
We have packaged the data for downloading.

**Comment by SizeWu** [comment]
Hi! Thanks for preparing and open-sourcing alll of these datasets. I noticed that you use the LA images in MIMIC-IT. May I know wether you applied in-context tuning when training the model or the LA images were just used in ordinary QA format?
