### ISSUE TITLE
[Question] Image patch representation in this work

### ISSUE THREAD

**Issue by cydiachen** [PKU-YuanGroup/MoE-LLaVA#43]
### Question

Hello. 
Firstly I will thank your assistance in debugging Qwen1.5 problem. I have achieved remarkable performance on Qwen1.5.
I am now working on intergrating your codebase with LLaVA-Next (Aiming to intergrate the high-resolution support). I am now came up with a question about image patch representation of your code. 

As is shown in Official LLaVA repo, the image feature map are flatten explicitly. But in your implementation, I did not find any operation to flatten image features. I am curious about the organization of image features in your work.
![image](https://github.com/PKU-YuanGroup/MoE-LLaVA/assets/26337720/5dfc8e4f-784e-4fff-a5e9-6c4815a6dd1c)
![image](https://github.com/PKU-YuanGroup/MoE-LLaVA/assets/26337720/b3393ecb-b62b-46f3-bdbf-464a97580d24)

**Comment by LinB203** [comment]
The output of the clip image encoder is already flat tokens.
