### ISSUE TITLE
supports Chinese or multiple images?

### ISSUE THREAD

**Issue by BaoyanWang** [PKU-YuanGroup/MoE-LLaVA#5]
Thank you for your work! I'm wondering, does the model you've developed support Chinese and multiple images?

**Comment by LinB203** [comment]
**For Chinese language support:** this issue depends a lot on LLM, qwen-1.8B supports Chinese, so MoE-LLaVA-Qwen certainly does. However, Phi2 does not support Chinese, so MoE-LLaVA-Phi2 do not support Chinese.
**Multi-image:** Our code supports multi-image training, multi-video training, and even image-video training together, however we have not released this version for the time being.

**Comment by lucasjinreal** [comment]
Deos MoE-LLaVA-Qwen available?

**Comment by LinB203** [comment]
> Deos MoE-LLaVA-Qwen available?

Sure. 
https://github.com/PKU-YuanGroup/MoE-LLaVA?tab=readme-ov-file#-model-zoo
