### ISSUE TITLE
Very bad at language ability

### ISSUE THREAD

**Issue by lucasjinreal** [PKU-YuanGroup/MoE-LLaVA#6]
![image](https://github.com/PKU-YuanGroup/MoE-LLaVA/assets/21303438/7cef5c53-2c0f-4153-997a-d278478351f5)

**Comment by LinB203** [comment]
Check them.

https://github.com/PKU-YuanGroup/MoE-LLaVA/issues/3#issuecomment-1916162040
https://github.com/PKU-YuanGroup/MoE-LLaVA/issues/5#issuecomment-1918518044
